// Regenerate the lightweight Clara truck from the existing particle study.
// Run: node scripts/generar-camion.cjs
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname, '..');
const source = process.argv[2] ? JSON.parse(fs.readFileSync(process.argv[2], 'utf8'))
  : vm.runInNewContext(fs.readFileSync(path.join(root, 'lab-camion-data.js'), 'utf8') + ';TRUCK');
const yaw = .48, tilt = .14, count = 4810;
const points = source.map((q, i) => {
  const x = q[0]*Math.cos(yaw)+q[2]*Math.sin(yaw);
  const z = -q[0]*Math.sin(yaw)+q[2]*Math.cos(yaw);
  return {values:[x, -q[1]*Math.cos(tilt)+z*Math.sin(tilt)-.09,
    q[1]*Math.sin(tilt)+z*Math.cos(tilt), q[6], ...q.slice(0,3),
    // Local tyre coordinates retained for rigid rotation around each axle.
    q[7] ?? (Math.abs(q[2])>.17 && Math.hypot(q[0]-(q[0]<0?-.4179:.54),q[1]+.2919)<.343
      ? (q[0]<0?1:2) : 0)],
    // Front is negative X. Prioritize cab/grille/steps over the tyre surface.
    weight: q[0]<-.35 ? (q[1]>-.20 ? 2.2 : 1.35) : 1, index:i};
});
const key = p => `${Math.round(p.values[0]/.018)},${Math.round(p.values[1]/.018)}`;
const depth = new Map();
for (const p of points) depth.set(key(p), Math.max(depth.get(key(p)) ?? -99, p.values[2]));
const visible = points.filter(p => p.values[2] >= depth.get(key(p))-.07);
// Deterministic weighted sampling without replacement; preserve particle count
// and identities in the morph instead of adding transient extra particles.
for (const p of visible) {
  let hash = Math.imul(p.index+1, 0x45d9f3b);
  hash = Math.imul(hash ^ (hash >>> 16), 0x45d9f3b);
  const u = ((hash ^ (hash >>> 16)) >>> 0) / 4294967296;
  p.rank = -Math.log(Math.max(1e-9,u))/p.weight;
}
visible.sort((a,b)=>a.rank-b.rank);
if (visible.length<count) throw new Error('Insufficient visible surface points');
const sampled = visible.slice(0,count).map(p=>p.values.map(v=>+v.toFixed(4)));
fs.writeFileSync(path.join(root,'clara-camion-modelo.js'),
  '// Generated by scripts/generar-camion.cjs; see scripts/muestrear-camion.py for OBJ wheel segmentation.\n' +
  '// Front three-quarter view, denser cab/grille; rear surfaces filtered offline.\n' +
  'const CLARA_TRUCK_MODEL='+JSON.stringify(sampled)+';\n' +
  'if(typeof module!=="undefined" && module.exports) module.exports=CLARA_TRUCK_MODEL;\n');
console.log(`Truck: ${sampled.length} particles, yaw ${yaw} rad; ${visible.length} visible candidates.`);
